### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by RDaneelOlivav** [sophiagu/stable-baselines-tf2#1]
Followed the setps and it continues to have this issue in Tensorflow2
Any ideas why?

**Comment by sophiagu** [comment]
Thanks for bringing this up! From my experience, anything related to 'tensorflow.contrib' is due to the compatibility issue to transport from TF1 to TF2. And the most likely reason here is that the TF2 library has been updated after this repo's creation (e.g. they may have removed some modules that they initially supported).

**Comment by sophiagu** [comment]
Hey I just found this relevant [stack overflow](https://stackoverflow.com/questions/55082483/why-can-i-not-import-tensorflow-contrib-i-get-an-error-of-no-module-named-tenso) post.

Sorry this repo is not being actively managed. You can follow the steps above and fix the issue in your local fork, or (better) merge your fix into this repo so other people can benefit from your effort! thanks in advance for that
